#! /bin/bash

# Default values
CACHE=0
CONFIG_FILE="config.ini"

# Parse command line arguments
while getopts ":c" opt; do
  case ${opt} in
    c )
      CACHE=1
      ;;
    \? )
      echo "Invalid Option: -$OPTARG" 1>&2
      exit 1
      ;;
  esac
done
shift $((OPTIND -1))

# Check if config file exists and read docker_name
if [ -f "$CONFIG_FILE" ]; then
    IMAGE_NAME=$(awk -F '=' '/DOCKER_NAME/ {print $2}' $CONFIG_FILE)
else
    echo "Config file not found: $CONFIG_FILE"
    exit 1
fi

# Check if image name was provided as argument
if [ -n "$1" ]
then
    IMAGE_NAME=$1
fi

mkdir -p .temp

docker build --build-arg CACHE=$CACHE -t $IMAGE_NAME .
