openapi: 3.0.1
info:
  version: 1.0.0
  description: An API to control a Firefox browser instance
  title: Autobrowser
servers:
  - url: https://localhost
    description: Local server
paths:
  /closeTabById:
    post:
      summary: Close a tab by its ID. Tab IDs can be found in the /tabsList endpoint, they are also returned by the /openTab endpoint
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tab_id:
                  type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                    enum: ['OK']
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  mesage:
                    type: string
                    enum: ['timeout']
        '400':
          description: Unknown server error - see message for details
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string

  /tabsList:
    get:
      summary: Get list of tabs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message: 
                    type: string
                    enum: ['OK']
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        url:
                          type: string
                        title:
                          type: string
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                    enum: ['Timeout waiting for tabsList']
                  result:
                    type: string
                    enum: ['timeout']
        '400'
          description: Error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [false]

  /openTab:
    post:
      summary: Open a new tab
      requestBody:
        content:
          application/json:
            schema:
              properties:
                url:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                  result:
                    type: integer
        '400':
          description: Error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [false]
                  
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                    enum: ['Timeout waiting for openTab']
                  result:
                    type: string
                    enum: ['timeout']

  /injectScript:
    post:
      summary: Inject a script
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tab_id:
                  type: string
                code:
                  type: string
                timeout:
                  type: integer
      responses:
        '200':
            description: OK - this return code means only that the script was successfully injected, any errors raised by the script in the browser are also returned under this code.
            content:
              application/json:
                schema:
                  properties:
                    status:
                      type: string
                      enum: ['success']
                    message:
                      type: string
                    result:
                      type: string
          '400':
            description: Error - this signals an error with script injection, not an error caused by the execution of the injected script.
            content:
              application/json:
                schema:
                  properties:
                    status:
                      type: string
                      enum: ['error']
                    message:
                      type: string
                    result:
                      type: boolean
                      enum: [false]
                    
          '408':
            description: Timeout error
            content:
              application/json:
                schema:
                  properties:
                    status:
                      type: string
                      enum: ['error']
                    message:
                      type: string
                      enum: ['Timeout waiting for injectScript']
                    result:
                      type: string
                      enum: ['timeout']
          '500':
            description: An unknown server error
            content:
              application/json:
                schema:
                  properties:
                    status:
                      type: string
                      enum: ['error']
                    message:
                      type: string
                      enum: ['Unknown server error occured. Failed to receive a result from the browser.']
                    result:
                      type: boolean
                      enum: [false]
  /waitForElement:
    post:
      summary: Wait for an element to become available in the page's DOM
      requestBody:
        content:
          application/json:
            schema:
              properties:
                tab_id:
                  type: integer
                selector:
                  description: This is a CSS Path selector that can be used with document.querySelector()
                  type: string
                timeout:
                  description: Amount of time (in seconds) to wait for the element to become available
                  type: integer
                  default: 60
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [true]
        '400':
          description: Error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [false]
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                    enum: ['Timeout waiting for waitForElement']
                  result:
                    type: string
                    enum: ['timeout']

  /getTabHTML/{tab_id}:
    get:
      summary: Get HTML of a tab
      parameters:
        - name: tab_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                  result:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [false]
                  
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                    enum: ['Timeout waiting for getTabHTML']
                  result:
                    type: string
                    enum: ['timeout']

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: The service is up and running
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [true]

  /search:
    get:
      summary: Execute a Google search for a given query, openning a new tab. The tab is closed after the search results are returnd.'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                query:
                  type: string
                timeout:
                  type: integer
                  default: 60
                max_results:
                  type: integer
                  default: 20
      responses:
        '200':
          description: Successfully executed the search, returning the search results
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['success']
                  message:
                    type: string
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        url:
                          type: string
                        snippet:
                          type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                  result:
                    type: boolean
                    enum: [false]
                  
        '408':
          description: Timeout error
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    enum: ['error']
                  message:
                    type: string
                    enum: ['Timeout waiting for search']
                  result:
                    type: string
                    enum: ['timeout']